### GET ALL EVENT PARTICIPANTS FOR ALL EVENTS
GET http://localhost:5000/events/ep
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYyMTY5MjkzLCJleHAiOjE3NjIyNTU2OTN9.cxilF4EDmjyhgZMflpSfSVUM67IhYVgpp1cgDAEPJWA
Content-Type: application/json

### REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "ts@gmail.com", "password": "sifra123"
}

### LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com", "password": "sifra123" 
}

### GET /EVENTS
GET http://localhost:5000/events/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYxODMxNzI0LCJleHAiOjE3NjE5MTgxMjR9.VC_7zC2Qv_ECiFCIjm6QRJyyLsAI1Kp3paGDVnSN_0E

### GET /EVENTS/FILTERED
GET http://localhost:5000/events?location=Stark Arena&type=Basketball
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYxNzI4MTc3LCJleHAiOjE3NjE4MTQ1Nzd9.xzBBqkejKs_6buq1M9w3Ppu_ooMnHJO7QZBdnTippBg

### GET /EVENTS LOCATIONS
GET http://localhost:5000/events/location
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYxNzI4MTc3LCJleHAiOjE3NjE4MTQ1Nzd9.xzBBqkejKs_6buq1M9w3Ppu_ooMnHJO7QZBdnTippBg

### GET /EVENTS TYPES
GET http://localhost:5000/events/type
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYxNzI4MTc3LCJleHAiOjE3NjE4MTQ1Nzd9.xzBBqkejKs_6buq1M9w3Ppu_ooMnHJO7QZBdnTippBg

### POST /EVENTS
POST http://localhost:5000/events
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYxNzM1ODg2LCJleHAiOjE3NjE4MjIyODZ9.g3xtq_HDilUAT-GY6CXkgiP6KHVtSAMU-71TeQPl8-s
Content-Type: application/json

{
    "title":"Odbrana diplomskog",
    "description": "odbrana diplomskog u VTSNS",
    "timestamp": 1761753600000,
    "location": "Novi Sad",
    "type": "Graduation",
    "role": "creator"
}

### PUT /EVENT
PUT http://localhost:5000/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYxNzM1ODg2LCJleHAiOjE3NjE4MjIyODZ9.g3xtq_HDilUAT-GY6CXkgiP6KHVtSAMU-71TeQPl8-s
Content-Type: application/json

{
    "title":"Utakmica kosarke",
    "description": "Zvezda - Baskonia",
    "timestamp": 1761753600000,
    "location": "Stark Arena",
    "type": "Basketball",
    "role": "visitor"
}

### DELETE /EVENT
DELETE http://localhost:5000/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYxNzI4MTc3LCJleHAiOjE3NjE4MTQ1Nzd9.xzBBqkejKs_6buq1M9w3Ppu_ooMnHJO7QZBdnTippBg


### POST RESET PASSWORD 
POST http://localhost:5000/auth/forgot-password/
Content-Type: application/json

{
    "email":"ts@gmail.com"
}

### Password reset
POST http://localhost:5000/auth/reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzYyMTYxNzIxLCJleHAiOjE3NjIxNjUzMjF9.p98YAVIz5dFeawEAuFXTVx8TGKa5TVk5EgQTD8W0qAU
Content-Type: application/json

{
    "password":"sifra1234"
}

### ATTENDANCE OVERVIEW
GET http://localhost:5000/events/attendance
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYyMTY5NjY1LCJleHAiOjE3NjIyNTYwNjV9.m-k_0nNsU182NpxT3_qe4JPn7B85ki6iTSXHro_L_dA
Content-Type: application/json