### TEST GET/WEBSIT
GET http://localhost:5000

### REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "tst", "password": "tst"
}

### LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com", "password": "sifra123" 
}

### GET /EVENTS
GET http://localhost:5000/events
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYwOTU4OTAxLCJleHAiOjE3NjEwNDUzMDF9.lbX7x5U_NyUCjB6m-Sz4u4ipm2Fo7ovUV6QzLK5LNHU

### POST /EVENTS
POST http://localhost:5000/events
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYwOTU4OTAxLCJleHAiOjE3NjEwNDUzMDF9.lbX7x5U_NyUCjB6m-Sz4u4ipm2Fo7ovUV6QzLK5LNHU
Content-Type: application/json

{
    "title":"Kosarkaska utakmica",
    "description": "Zvezda - Real Madrid",
    "timestamp": 1760982604630,
    "location": "Belgrade Arena",
    "type": "Basketball"
}

### PUT /EVENT
PUT http://localhost:5000/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYwOTU4OTAxLCJleHAiOjE3NjEwNDUzMDF9.lbX7x5U_NyUCjB6m-Sz4u4ipm2Fo7ovUV6QzLK5LNHU
Content-Type: application/json

{
    "title":"Utakmica kosarke",
    "description": "Zvezda - Baskonia",
    "timestamp": 1760993404630,
    "location": "Stark Arena",
    "type": "Basketball"
}

### DELETE /EVENT
DELETE http://localhost:5000/events/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzYwOTU4OTAxLCJleHAiOjE3NjEwNDUzMDF9.lbX7x5U_NyUCjB6m-Sz4u4ipm2Fo7ovUV6QzLK5LNHU
